---
abstract: "Release tests making sure all MANIFEST'ed modules pass use_oK()"
author:
  - 'Alexei Znamensky <russoz@cpan.org>'
build_requires:
  English: 0
  File::Find: 0
  File::Temp: 0
  Test::More: 0.88
  perl: 5.006
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200008, CPAN::Meta::Converter version 2.110930'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-Plugin-Test-UseAllModules
requires:
  Dist::Zilla::Plugin::InlineFiles: 0
  Moose: 0
  Test::UseAllModules: 0.13
  namespace::autoclean: 0
resources:
  homepage: http://github.com/russoz/Dist-Zilla-Plugin-Test-UseAllModules
  repository: http://github.com/russoz/Dist-Zilla-Plugin-Test-UseAllModules
version: 0.001
